<?php

/**
 * @file
 * The new information architecture as data, for apply.php.
 *
 * Generated by tools/package_drupal.py from design/ia.json; do not edit by hand.
 */

if (PHP_SAPI !== 'cli') {
  exit;
}

return [
  'menus' => [
    'main' => [
      [
        'title' => 'Parents',
        'link' => '/parents',
        'children' => [
          [
            'title' => '[Most requested]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Student Attendance',
                'link' => '/parents/student-attendance',
              ],
              [
                'title' => 'School Cash Online',
                'link' => '/parents/school-cash-online',
              ],
              [
                'title' => 'MyEd Parent Portal: Request Assistance',
                'link' => '/parents/myed-parent-portal-request-assistance',
              ],
              [
                'title' => 'Learning Updates',
                'link' => '/parents/learning-updates',
              ],
              [
                'title' => 'Universal Hot Lunch @ McRoberts',
                'link' => '/parents/universal-hot-lunch-mcroberts',
              ],
            ],
          ],
          [
            'title' => 'Welcome to McRoberts',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Grade 7 (Incoming 8) Program Planning',
                'link' => '/students/program-planning/grade-7-incoming-8-program-planning',
              ],
              [
                'title' => 'French Immersion Program',
                'link' => '/about-us',
              ],
              [
                'title' => 'Catchment',
                'link' => '/about-us/catchment',
              ],
              [
                'title' => 'Presentations for Parents',
                'link' => '/parents/presentations-parents',
              ],
            ],
          ],
          [
            'title' => 'Resources for Parents',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Updating Student Contact Information',
                'link' => '/parents/updating-student-contact-information',
              ],
              [
                'title' => 'Student Accident Insurance',
                'link' => '/parents/student-accident-insurance',
              ],
              [
                'title' => 'Athletics Info for Parents',
                'link' => '/parents/athletics-info-parents',
              ],
              [
                'title' => 'Donations',
                'link' => '/parents/donations',
              ],
              [
                'title' => 'Helpful Links',
                'link' => '/parents/helpful-links',
              ],
            ],
          ],
          [
            'title' => 'Important information for parents',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Responsible Use of Technology Info',
                'link' => '/parents/responsible-use-technology-info',
              ],
              [
                'title' => 'Violence Threat Risk Assessment (VTRA) Protocol and Fair Notice',
                'link' => '/parents/violence-threat-risk-assessment-vtra-protocol-and-fair-notice',
              ],
              [
                'title' => 'District Concussion Protocol',
                'link' => '/parents/district-concussion-protocol',
              ],
              [
                'title' => 'Snow and Extreme Weather Protocols',
                'link' => '/school-calendar/snow-and-extreme-weather-protocols',
              ],
            ],
          ],
          [
            'title' => 'Parent Advisory Committee (PAC)',
            'link' => '/parents/pac',
            'children' => [
              [
                'title' => 'PAC Meeting Agendas',
                'link' => '/parents/pac/meeting-agendas',
              ],
              [
                'title' => 'PAC Meeting Minutes',
                'link' => '/parents/pac/meeting-minutes',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => 'Students',
        'link' => '/students',
        'children' => [
          [
            'title' => '[Most requested]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Student Login',
                'link' => '/students/student-login',
              ],
              [
                'title' => 'MyEd Student Portal: Request Assistance',
                'link' => '/students/myed-student-portal-request-assistance',
              ],
              [
                'title' => 'Counselling Centre',
                'link' => '/students/counselling-centre',
              ],
              [
                'title' => 'Career Centre Information',
                'link' => '/students/career-centre-information',
              ],
              [
                'title' => 'Grad 2027',
                'link' => '/students/grad',
              ],
            ],
          ],
          [
            'title' => 'Academic Support',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Program Planning',
                'link' => '/students/program-planning',
              ],
              [
                'title' => 'Grade 7 (Incoming 8) Program Planning',
                'link' => '/students/program-planning/grade-7-incoming-8-program-planning',
              ],
              [
                'title' => 'Grade 8 - 11 (Incoming 9 - 12) Program Planning',
                'link' => '/students/program-planning/grade-8-11-incoming-9-12-program-planning',
              ],
              [
                'title' => 'Online Learning with Richmond Virtual School (RVS)',
                'link' => '/students/online-learning-richmond-virtual-school-rvs',
              ],
              [
                'title' => 'Core Competencies',
                'link' => '/students/core-competencies',
              ],
              [
                'title' => 'Personal Learning Time (PLT)',
                'link' => '/school-calendar/personal-learning-time-plt',
              ],
            ],
          ],
          [
            'title' => 'Required for Graduation',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Provincial Graduation Assessments',
                'link' => '/students/provincial-graduation-assessments',
              ],
              [
                'title' => 'Capstone/Career-Life Connections (CLC)',
                'link' => '/students/career-education/capstone-career-life-connections-clc',
              ],
              [
                'title' => 'Career Education Volunteer Hours',
                'link' => '/students/career-education/career-education-volunteer-hours',
              ],
            ],
          ],
          [
            'title' => 'Career Exploration',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Post-Secondary Info',
                'link' => '/students/career-centre-information#post-secondary-info',
              ],
              [
                'title' => 'Reference Letters',
                'link' => '/students/reference-letters',
              ],
              [
                'title' => 'Career Education',
                'link' => '/students/career-education',
              ],
              [
                'title' => 'Career Education 8 & 9',
                'link' => '/students/career-education/career-education-8-9',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => 'School Calendar',
        'link' => '/school-calendar',
        'children' => [
          [
            'title' => '[Most requested]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Bell Schedule',
                'link' => '/school-calendar/bell-schedule',
              ],
            ],
          ],
          [
            'title' => '[More]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Personal Learning Time (PLT)',
                'link' => '/school-calendar/personal-learning-time-plt',
              ],
              [
                'title' => 'Snow and Extreme Weather Protocols',
                'link' => '/school-calendar/snow-and-extreme-weather-protocols',
              ],
              [
                'title' => 'Subscribe to our calendar',
                'link' => 'webcal://mcroberts.sd38.bc.ca/calendar-feed.ics',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => 'News',
        'link' => '/news',
        'children' => [
          [
            'title' => '[Most requested]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Newsletters',
                'link' => '/news/newsletters',
              ],
            ],
          ],
          [
            'title' => '[More]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'School Learning Story',
                'link' => '/school-learning-story',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => 'Extra-Curricular',
        'link' => '/extra-curricular',
        'children' => [
          [
            'title' => '[Most requested]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Strikers Athletics',
                'link' => '/extra-curricular/strikers-athletics',
              ],
              [
                'title' => 'Club Directory',
                'link' => '/extra-curricular/club-directory',
              ],
            ],
          ],
          [
            'title' => 'Resources for Parents',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Athletics Info for Parents',
                'link' => '/parents/athletics-info-parents',
              ],
              [
                'title' => 'District Concussion Protocol',
                'link' => '/parents/district-concussion-protocol',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => 'Library',
        'link' => '/library',
        'children' => [
          [
            'title' => '[Most requested]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Library Catalogue',
                'link' => 'https://search.follettsoftware.com/metasearch/ui/21989',
              ],
              [
                'title' => 'Digital Resources',
                'link' => '/library/digital-resources',
              ],
            ],
          ],
          [
            'title' => '[More]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Read & Listen',
                'link' => '/library/read-listen',
              ],
              [
                'title' => 'Make & Play',
                'link' => '/library/make-play',
              ],
              [
                'title' => 'Q & A',
                'link' => '/library/q-and-a',
              ],
              [
                'title' => 'Biblio Bites: A Monthly Library Newsletter',
                'link' => '/library/biblio-bites',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => 'About Us',
        'link' => '/about-us',
        'children' => [
          [
            'title' => '[Most requested]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Contact Us',
                'link' => '/contact-us',
              ],
              [
                'title' => 'Our Staff',
                'link' => '/about-us/our-staff',
              ],
            ],
          ],
          [
            'title' => '[More]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Mission Statement',
                'link' => '/about-us/mission-statement',
              ],
              [
                'title' => 'French Immersion Program',
                'link' => '/about-us',
              ],
              [
                'title' => 'Catchment',
                'link' => '/about-us/catchment',
              ],
              [
                'title' => 'Donations',
                'link' => '/parents/donations',
              ],
            ],
          ],
        ],
      ],
    ],
    'utility' => [
      [
        'title' => 'Student Absent?',
        'link' => '/parents/student-attendance',
      ],
      [
        'title' => '604-668-6600 (Ext. 1)',
        'link' => 'tel:+16046686600,1',
      ],
      [
        'title' => 'MyEducation BC',
        'link' => 'https://myeducation.gov.bc.ca/aspen/logon.do',
      ],
      [
        'title' => 'School Cash Online',
        'link' => 'https://schoolcashonline.com/',
      ],
      [
        'title' => 'Office 365',
        'link' => 'https://portal.office.com',
      ],
      [
        'title' => 'Contact Us',
        'link' => '/contact-us',
      ],
    ],
    'footer' => [
      [
        'title' => 'Get in Touch',
        'link' => 'route:<nolink>',
        'children' => [
          [
            'title' => 'Contact Us',
            'link' => '/contact-us',
          ],
          [
            'title' => 'Our Staff',
            'link' => '/about-us/our-staff',
          ],
          [
            'title' => 'Student Absent?',
            'link' => '/parents/student-attendance',
          ],
          [
            'title' => '604-668-6600 (Ext. 1)',
            'link' => 'tel:+16046686600,1',
          ],
          [
            'title' => 'mcroberts@sd38.bc.ca',
            'link' => 'mailto:mcroberts@sd38.bc.ca',
          ],
          [
            'title' => '8980 Williams Road',
            'link' => 'https://maps.apple.com/?q=8980%20Williams%20Road%20Richmond%20BC%20V7A%201G6%20CA',
          ],
        ],
      ],
      [
        'title' => 'Helpful Links',
        'link' => 'route:<nolink>',
        'children' => [
          [
            'title' => 'MyEducation BC',
            'link' => 'https://myeducation.gov.bc.ca/aspen/logon.do',
          ],
          [
            'title' => 'School Cash Online',
            'link' => 'https://schoolcashonline.com/',
          ],
          [
            'title' => 'Office 365',
            'link' => 'https://portal.office.com',
          ],
          [
            'title' => 'Subscribe to our calendar',
            'link' => 'webcal://mcroberts.sd38.bc.ca/calendar-feed.ics',
          ],
          [
            'title' => 'School District No. 38 (Richmond)',
            'link' => 'https://www.sd38.bc.ca',
          ],
        ],
      ],
      [
        'title' => 'Important information for parents',
        'link' => 'route:<nolink>',
        'children' => [
          [
            'title' => 'Snow and Extreme Weather Protocols',
            'link' => '/school-calendar/snow-and-extreme-weather-protocols',
          ],
          [
            'title' => 'District Concussion Protocol',
            'link' => '/parents/district-concussion-protocol',
          ],
          [
            'title' => 'Violence Threat Risk Assessment (VTRA) Protocol and Fair Notice',
            'link' => '/parents/violence-threat-risk-assessment-vtra-protocol-and-fair-notice',
          ],
          [
            'title' => 'Responsible Use of Technology Info',
            'link' => '/parents/responsible-use-technology-info',
          ],
          [
            'title' => 'ERASE',
            'link' => 'https://www2.gov.bc.ca/gov/content/erase',
          ],
        ],
      ],
    ],
    'hub-links' => [
      [
        'title' => '[Home]',
        'link' => 'route:<front>',
        'children' => [
          [
            'title' => 'Parents',
            'link' => '/parents',
            'children' => [
              [
                'title' => 'Student Attendance',
                'link' => '/parents/student-attendance',
              ],
              [
                'title' => 'School Calendar',
                'link' => '/school-calendar',
              ],
              [
                'title' => 'Newsletters',
                'link' => '/news/newsletters',
              ],
              [
                'title' => 'Bell Schedule',
                'link' => '/school-calendar/bell-schedule',
              ],
              [
                'title' => 'School Cash Online',
                'link' => '/parents/school-cash-online',
              ],
              [
                'title' => 'MyEd Parent Portal: Request Assistance',
                'link' => '/parents/myed-parent-portal-request-assistance',
              ],
              [
                'title' => 'Universal Hot Lunch @ McRoberts',
                'link' => '/parents/universal-hot-lunch-mcroberts',
              ],
              [
                'title' => 'Contact Us',
                'link' => '/contact-us',
              ],
            ],
          ],
          [
            'title' => 'Students',
            'link' => '/students',
            'children' => [
              [
                'title' => 'Student Login',
                'link' => '/students/student-login',
              ],
              [
                'title' => 'Counselling Centre',
                'link' => '/students/counselling-centre',
              ],
              [
                'title' => 'Career Centre Information',
                'link' => '/students/career-centre-information',
              ],
              [
                'title' => 'Grad 2027',
                'link' => '/students/grad',
              ],
              [
                'title' => 'Program Planning',
                'link' => '/students/program-planning',
              ],
              [
                'title' => 'Bell Schedule',
                'link' => '/school-calendar/bell-schedule',
              ],
              [
                'title' => 'Club Directory',
                'link' => '/extra-curricular/club-directory',
              ],
              [
                'title' => 'Library',
                'link' => '/library',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '[Library Learning Commons]',
        'link' => '/library',
        'children' => [
          [
            'title' => '[Cards]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Library Catalogue',
                'link' => '/library/library-catalogue',
              ],
              [
                'title' => 'Digital Resources',
                'link' => '/library/digital-resources',
              ],
            ],
          ],
          [
            'title' => '[Cards]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Read & Listen',
                'link' => '/library/read-listen',
              ],
              [
                'title' => 'Make & Play',
                'link' => '/library/make-play',
              ],
              [
                'title' => 'Q & A',
                'link' => '/library/q-and-a',
              ],
              [
                'title' => 'Biblio Bites: A Monthly Library Newsletter',
                'link' => '/library/biblio-bites',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '[Grad 2027]',
        'link' => '/students/grad',
        'children' => [
          [
            'title' => 'Required for Graduation',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Provincial Graduation Assessments',
                'link' => '/students/provincial-graduation-assessments',
              ],
              [
                'title' => 'Capstone/Career-Life Connections (CLC)',
                'link' => '/students/career-education/capstone-career-life-connections-clc',
              ],
              [
                'title' => 'Career Education Volunteer Hours',
                'link' => '/students/career-education/career-education-volunteer-hours',
              ],
            ],
          ],
          [
            'title' => 'Post-Secondary Info',
            'link' => '/students/career-centre-information#post-secondary-info',
            'children' => [
              [
                'title' => 'Career Centre Information',
                'link' => '/students/career-centre-information',
              ],
              [
                'title' => 'Reference Letters',
                'link' => '/students/reference-letters',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '[Program Planning]',
        'link' => '/students/program-planning',
        'children' => [
          [
            'title' => '[Cards]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Grade 7 (Incoming 8) Program Planning',
                'link' => '/students/program-planning/grade-7-incoming-8-program-planning',
              ],
              [
                'title' => 'Grade 8 - 11 (Incoming 9 - 12) Program Planning',
                'link' => '/students/program-planning/grade-8-11-incoming-9-12-program-planning',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '[Career Education]',
        'link' => '/students/career-education',
        'children' => [
          [
            'title' => '[Cards]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Career Education 8 & 9',
                'link' => '/students/career-education/career-education-8-9',
              ],
              [
                'title' => 'Capstone/Career-Life Connections (CLC)',
                'link' => '/students/career-education/capstone-career-life-connections-clc',
              ],
              [
                'title' => 'Career Education Volunteer Hours',
                'link' => '/students/career-education/career-education-volunteer-hours',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '[Parent Advisory Committee (PAC)]',
        'link' => '/parents/pac',
        'children' => [
          [
            'title' => '[Cards]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'PAC Meeting Agendas',
                'link' => '/parents/pac/meeting-agendas',
              ],
              [
                'title' => 'PAC Meeting Minutes',
                'link' => '/parents/pac/meeting-minutes',
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '[District Concussion Protocol]',
        'link' => '/parents/district-concussion-protocol',
        'children' => [
          [
            'title' => '[Cards]',
            'link' => 'route:<nolink>',
            'children' => [
              [
                'title' => 'Concussion Awareness, Response and Management',
                'link' => '/parents/district-concussion-protocol/concussion-awareness-response-and-management',
              ],
            ],
          ],
        ],
      ],
    ],
  ],
  'aliases' => [
    [
      'old' => '/students-0',
      'new' => '/students',
      'title' => 'Students',
    ],
    [
      'old' => '/students/grad-2026',
      'new' => '/students/grad',
      'title' => 'Grad 2027',
    ],
    [
      'old' => '/students/career-education-volunteer-hours',
      'new' => '/students/career-education',
      'title' => 'Career Education',
    ],
    [
      'old' => '/students/career-education-volunteer-hours/career-education-8-9',
      'new' => '/students/career-education/career-education-8-9',
      'title' => 'Career Education 8 & 9',
    ],
    [
      'old' => '/students/career-education-volunteer-hours/capstonecareer-life-connections-clc',
      'new' => '/students/career-education/capstone-career-life-connections-clc',
      'title' => 'Capstone/Career-Life Connections (CLC)',
    ],
    [
      'old' => '/students/career-education-volunteer-hours/career-education-volunteer-hour-requirements',
      'new' => '/students/career-education/career-education-volunteer-hours',
      'title' => 'Career Education Volunteer Hours',
    ],
    [
      'old' => '/information/about-us',
      'new' => '/about-us',
      'title' => 'About Us',
    ],
    [
      'old' => '/information/about-us/mission-statement',
      'new' => '/about-us/mission-statement',
      'title' => 'Mission Statement',
    ],
    [
      'old' => '/information/our-staff',
      'new' => '/about-us/our-staff',
      'title' => 'Our Staff',
    ],
    [
      'old' => '/information/catchment',
      'new' => '/about-us/catchment',
      'title' => 'McRoberts Catchment',
    ],
    [
      'old' => '/information/contact-us',
      'new' => '/contact-us',
      'title' => 'Contact Us',
    ],
    [
      'old' => '/information/bell-schedule',
      'new' => '/school-calendar/bell-schedule',
      'title' => 'Timetable Structure 2026-2027',
    ],
    [
      'old' => '/information/personal-learning-time-plt',
      'new' => '/school-calendar/personal-learning-time-plt',
      'title' => 'Personal Learning Time (PLT)',
    ],
    [
      'old' => '/information/snow-and-extreme-weather-protocols',
      'new' => '/school-calendar/snow-and-extreme-weather-protocols',
      'title' => 'Snow and Extreme Weather Protocols',
    ],
    [
      'old' => '/information/donations',
      'new' => '/parents/donations',
      'title' => 'Donations',
    ],
    [
      'old' => '/information/district-concussion-protocol',
      'new' => '/parents/district-concussion-protocol',
      'title' => 'District Concussion Protocol',
    ],
    [
      'old' => '/media/1069',
      'new' => '/parents/district-concussion-protocol/concussion-awareness-response-and-management',
      'title' => 'Concussion Awareness, Response and Management',
    ],
    [
      'old' => '/students/updating-student-contact-information',
      'new' => '/parents/updating-student-contact-information',
      'title' => 'Updating Student Contact Information',
    ],
    [
      'old' => '/parents/parent-advisory-committee-pac',
      'new' => '/parents/pac',
      'title' => 'Parent Advisory Committee (PAC)',
    ],
    [
      'old' => '/parents/parent-advisory-committee-pac/pac-meeting-agendas',
      'new' => '/parents/pac/meeting-agendas',
      'title' => 'PAC Meeting Agendas',
    ],
    [
      'old' => '/parents/parent-advisory-committee-pac/pac-meeting-minutes',
      'new' => '/parents/pac/meeting-minutes',
      'title' => 'PAC Meeting Minutes',
    ],
    [
      'old' => '/node/1813',
      'new' => '/library/biblio-bites',
      'title' => 'Biblio Bites: A Monthly Library Newsletter',
    ],
    [
      'old' => '/library/q',
      'new' => '/library/q-and-a',
      'title' => 'Q & A',
    ],
    [
      'old' => '/our-school-story/news/2024/02/sel-survey-january-2024',
      'new' => '/school-learning-story/news/2024/02/sel-survey-january-2024',
      'title' => 'SEL Survey January 2024',
    ],
    [
      'old' => '/our-school-story/news/2024/06/developing-community-through-awards',
      'new' => '/school-learning-story/news/2024/06/developing-community-through-awards',
      'title' => 'Developing Community Through Awards',
    ],
    [
      'old' => '/our-school-story/news/2024/09/mcroberts-mural',
      'new' => '/school-learning-story/news/2024/09/mcroberts-mural',
      'title' => 'McRoberts Mural',
    ],
    [
      'old' => '/our-school-story/news/2024/12/grade-8-student-mentor-connections',
      'new' => '/school-learning-story/news/2024/12/grade-8-student-mentor-connections',
      'title' => 'Grade 8 - Student Mentor Connections',
    ],
    [
      'old' => '/our-school-story/news/2025/03/mcroberts-teacher-book-club',
      'new' => '/school-learning-story/news/2025/03/mcroberts-teacher-book-club',
      'title' => 'McRoberts Teacher Book Club',
    ],
  ],
  'retired' => [
    [
      'old' => '/information',
      'new' => '/about-us',
      'title' => 'Information',
    ],
    [
      'old' => '/information-0',
      'new' => '/about-us',
      'title' => 'Information',
    ],
    [
      'old' => '/library/research-inquiry',
      'new' => '/library',
      'title' => 'Research & Inquiry',
    ],
    [
      'old' => '/parents/parent-advisory-committee-pac/pac-constitution-and-bylaws',
      'new' => '/parents/pac',
      'title' => 'PAC Constitution and Bylaws',
    ],
    [
      'old' => '/news/2026/08/back-school-schedules-and-calendars-0',
      'new' => '/news/2026/08/back-school-schedules-and-calendars',
      'title' => 'Back to School – Schedules and Calendars',
    ],
  ],
];
