"""Write content/INVENTORY.md (what the site contains) and content/corpus.txt (every phrase the live site shows).

corpus.txt is the reference for tools/check_copy.py: each visible phrase of the redesign must appear in it.
    python3 tools/inventory.py
"""
import html, json, re
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
C = ROOT / "content"


class Text(HTMLParser):
    SKIP = {"script", "style", "svg", "noscript", "head"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.out, self.skip = [], 0

    def handle_starttag(self, tag, attrs):
        if tag in self.SKIP:
            self.skip += 1
        for k, v in attrs:
            if k in ("title", "alt", "aria-label", "placeholder", "value") and v:
                self.out.append(v)

    def handle_endtag(self, tag):
        if tag in self.SKIP and self.skip:
            self.skip -= 1

    def handle_data(self, d):
        if not self.skip:
            self.out.append(d)


def norm(s):
    s = html.unescape(s).replace("﻿", "").replace(" ", " ")
    s = s.replace("’", "'").replace("‘", "'").replace("“", '"').replace("”", '"').replace("–", "-").replace("—", "-")
    return re.sub(r"\s+", " ", s).strip()


def main():
    index = json.loads((ROOT / "cache" / "index.json").read_text())
    chunks = []
    for key, meta in sorted(index.items()):
        if not meta.get("file"):
            continue
        p = Text()
        p.feed((ROOT / "cache" / "raw" / meta["file"]).read_text())
        chunks.extend(norm(x) for x in p.out if norm(x))
    ics = (ROOT / "cache" / "calendar-feed.ics").read_text()
    chunks.extend(norm(m.replace("\\,", ",")) for m in re.findall(r"^SUMMARY:(.*)$", ics, re.M))
    # the School Calendar page's own FullCalendar events (its grid shows them; the feed starts later)
    import sys
    sys.path.insert(0, str(ROOT / "tools"))
    from extract import read_fullcalendar
    if "/school-calendar" in index:
        chunks.extend(norm(e["title"]) for e in read_fullcalendar(ROOT / "cache" / "raw" / index["/school-calendar"]["file"]))
    seen, uniq = set(), []
    for c in chunks:
        if c not in seen:
            seen.add(c)
            uniq.append(c)
    (C / "corpus.txt").write_text("\n".join(uniq) + "\n")

    pages = json.loads((C / "pages.json").read_text())
    menu = json.loads((C / "menu.json").read_text())
    site = json.loads((C / "site.json").read_text())
    news = json.loads((C / "news.json").read_text())
    events = json.loads((C / "events.json").read_text())
    L = ["# Content inventory (generated by tools/inventory.py)", "",
         f"- School: **{site['name']}** - motto: *{site['motto']}*",
         f"- Address: {', '.join(site['address'])} - phone {site['phone']} - {site['email']}",
         f"- Logo: assets/content/{site['logo']} (original), header photo: assets/content/{site['headerImage']} (green-tinted, 1400x400)",
         f"- Pages: {len(pages)} - news items indexed: {len(news)} - calendar events (ICS feed + calendar page): {len(events)}", "",
         "## Main menu", ""]
    for m in menu:
        L.append(f"- [{m['title']}]({m['href']})")
        for c in m["children"]:
            L.append(f"  - [{c['title']}]({c['href']})")
    L += ["", "## Pages", "", "| path | type | title | words | children |", "|---|---|---|---|---|"]
    for k, p in sorted(pages.items()):
        words = len(re.sub(r"<[^>]+>", " ", p.get("body", "")).split())
        L.append(f"| {k} | {p['type']} | {p['title']} | {words} | {len(p.get('children', []))} |")
    L += ["", "## Front page blocks", ""]
    for b in site["frontBlocks"]:
        L.append(f"- `{b['id']}` - {b['heading'] or '(no heading)'}")
    (C / "INVENTORY.md").write_text("\n".join(L) + "\n")
    print("corpus phrases", len(uniq))


if __name__ == "__main__":
    main()
